# Generated by Django 5.2.12 on 2026-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_userprofile_hudud'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clinic_no',
            field=models.CharField(default='7', help_text='Poliklinika raqami (1–3 raqam), masalan 7.', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visit_type',
            field=models.CharField(default='OP', help_text='Muassasa turi qisqartmasi (2–3 harf), masalan OP — oylaviy poliklinika.', max_length=3),
        ),
    ]
