# Generated by Django 5.2.12 on 2026-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_clinic_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hudud_code',
            field=models.CharField(blank=True, db_index=True, help_text='Daftar hudud kodi (2–16 lotin harf yoki raqam, masalan FSH, QOQ, FARMRG).', max_length=16),
        ),
    ]
