# Generated by Django 5.2.14 on 2026-08-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(models.Migration):

    dependencies = [
        ("api", "0003_expand_hudud_code_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.CharField(db_index=True, max_length=24, unique=True)),
                ("lab_type", models.CharField(db_index=True, max_length=48)),
                ("source", models.CharField(default="upload", max_length=16)),
                ("status", models.CharField(db_index=True, default="tahlil_qilinmoqda", max_length=32)),
                ("text", models.TextField(blank=True)),
                ("job_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("img_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analyses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="api_analysi_user_id_754aab_idx")],
            },
        ),
    ]
