"""Klinik tashxis sinonimlari — dx_list.js dan generatsiya qilingan.

Qo'lda tahrirlamang: scripts/gen_dx_synonyms.py ni qayta ishga tushiring.
Har yozuv: (o'zbekcha/lotincha nom, ruscha sinonim, guruh).
"""

DX_SYNONYMS = (
    ('Ekzema (spongiotik dermatit)', 'экзема', 'Spongiotik'),
    ('Atopik dermatit', 'атопический дерматит', 'Spongiotik'),
    ('Allergik kontakt dermatit', 'аллергический контактный дерматит', 'Spongiotik'),
    ('Irritant kontakt dermatit', 'ирритантный контактный дерматит', 'Spongiotik'),
    ('Seboreyali dermatit', 'себорейный дерматит', 'Spongiotik'),
    ('Numulyar dermatit', 'нуммулярная экзема', 'Spongiotik'),
    ('Dishidrotik ekzema', 'дисгидротическая экзема', 'Spongiotik'),
    ('Staz dermatiti', 'застойный дерматит', 'Spongiotik'),
    ('Id-reaksiya', 'ид-реакция', 'Spongiotik'),
    ('Pityriasis rosea', 'розовый лишай Жибера', 'Spongiotik'),
    ('Psoriasis vulgaris', 'псориаз обыкновенный', 'Psoriaziform'),
    ('Pustulyoz psoriaz', 'пустулёзный псориаз', 'Psoriaziform'),
    ('Guttat psoriaz', 'каплевидный псориаз', 'Psoriaziform'),
    ('Psoriaziform dermatit', 'псориазиформный дерматит', 'Psoriaziform'),
    ('Pityriasis rubra pilaris', 'красный волосяной лишай Девержи', 'Psoriaziform'),
    ('Reyter sindromi (keratoderma blennorrhagica)', 'синдром Рейтера', 'Psoriaziform'),
    ('Xronik oddiy lixen (Vidal)', 'простой хронический лишай Видаля', 'Psoriaziform'),
    ('Lichen planus (qizil yassi temiratki)', 'красный плоский лишай', 'Lixenoid'),
    ('Lixenoid dori reaksiyasi', 'лихеноидная лекарственная реакция', 'Lixenoid'),
    ('Lichen sclerosus', 'склероатрофический лихен', 'Lixenoid'),
    ('Lichen nitidus', 'блестящий лишай', 'Lixenoid'),
    ("Diskoid qizil bo'richa", 'дискоидная красная волчанка', 'Lixenoid'),
    ("Sistem qizil bo'richa (teri)", 'системная красная волчанка', 'Lixenoid'),
    ('Dermatomiozit (teri)', 'дерматомиозит', 'Lixenoid'),
    ('Eritema multiforme', 'многоформная экссудативная эритема', 'Lixenoid'),
    ('Stiven-Jonson / TEN', 'синдром Стивенса-Джонсона', 'Lixenoid'),
    ('Fiksatsiyalangan dori eritemasi', 'фиксированная эритема', 'Lixenoid'),
    ('Graft-versus-host reaksiyasi', 'реакция трансплантат против хозяина', 'Lixenoid'),
    ('Pityriasis lichenoides', 'парапсориаз лихеноидный', 'Lixenoid'),
    ('Pemphigus vulgaris', 'пузырчатка вульгарная', 'Bullyoz'),
    ('Pemphigus foliaceus', 'пузырчатка листовидная', 'Bullyoz'),
    ('Vegetatsiyalanuvchi pemfigus', 'вегетирующая пузырчатка', 'Bullyoz'),
    ('Paraneoplastik pemfigus', 'паранеопластическая пузырчатка', 'Bullyoz'),
    ('Bullyoz pemfigoid', 'буллёзный пемфигоид', 'Bullyoz'),
    ('Homiladorlik pemfigoidi', 'пемфигоид беременных', 'Bullyoz'),
    ('Shilliq pardalar pemfigoidi', 'рубцующий пемфигоид', 'Bullyoz'),
    ('Dyuring gerpetiform dermatiti', 'герпетиформный дерматит Дюринга', 'Bullyoz'),
    ('Chiziqli IgA dermatozi', 'линейный IgA дерматоз', 'Bullyoz'),
    ('Epidermolysis bullosa acquisita', 'приобретённый буллёзный эпидермолиз', 'Bullyoz'),
    ('Porphyria cutanea tarda', 'поздняя кожная порфирия', 'Bullyoz'),
    ('Grover kasalligi', 'болезнь Гровера', 'Bullyoz'),
    ('Darier kasalligi', 'болезнь Дарье', 'Bullyoz'),
    ('Hailey-Hailey kasalligi', 'болезнь Хейли-Хейли', 'Bullyoz'),
    ('Granuloma annulare', 'кольцевидная гранулёма', 'Granulomatoz'),
    ('Sarkoidoz (teri)', 'саркоидоз кожи', 'Granulomatoz'),
    ('Nekrobioz lipoidika', 'липоидный некробиоз', 'Granulomatoz'),
    ('Yot jism granulemasi', 'гранулёма инородного тела', 'Granulomatoz'),
    ('Rheumatoid tugun', 'ревматоидный узелок', 'Granulomatoz'),
    ('Granulomatoz rozatsea', 'гранулематозная розацеа', 'Granulomatoz'),
    ('Teri sili (lupus vulgaris)', 'туберкулёз кожи, волчанка обыкновенная', 'Granulomatoz'),
    ('Leyshmanioz (teri)', 'кожный лейшманиоз', 'Granulomatoz'),
    ('Moxov (lepra)', 'лепра', 'Granulomatoz'),
    ('Leykotsitoklastik vaskulit', 'лейкоцитокластический васкулит', 'Vaskulit'),
    ('IgA vaskuliti (Shonlayn-Genox)', 'геморрагический васкулит', 'Vaskulit'),
    ('Tugunli poliarteriit (teri)', 'узелковый полиартериит', 'Vaskulit'),
    ('Pigmentli purpurali dermatoz', 'пигментный пурпурозный дерматоз', 'Vaskulit'),
    ('Livedoid vaskulopatiya', 'ливедоидная васкулопатия', 'Vaskulit'),
    ('Urtikar vaskulit', 'уртикарный васкулит', 'Vaskulit'),
    ('Piogen granulema', 'пиогенная гранулёма', 'Vaskulit'),
    ('Gemangioma', 'гемангиома', 'Vaskulit'),
    ('Kapillyar malformatsiya', 'капиллярная мальформация', 'Vaskulit'),
    ('Kaposi sarkomasi', 'саркома Капоши', 'Vaskulit'),
    ('Angiosarkoma', 'ангиосаркома', 'Vaskulit'),
    ('Bazillyar angiomatoz', 'бациллярный ангиоматоз', 'Vaskulit'),
    ('Eritema nodozum', 'узловатая эритема', 'Pannikulit'),
    ('Eritema induratum (Bazin)', 'индуративная эритема Базена', 'Pannikulit'),
    ('Lupus pannikuliti', 'волчаночный панникулит', 'Pannikulit'),
    ('Pankreatik pannikulit', 'панкреатический панникулит', 'Pannikulit'),
    ('Impetigo', 'импетиго', 'Infeksiya'),
    ('Follikulit', 'фолликулит', 'Infeksiya'),
    ('Furunkul / karbunkul', 'фурункул, карбункул', 'Infeksiya'),
    ('Sellyulit / erizipel', 'рожа, целлюлит', 'Infeksiya'),
    ('Dermatofitiya (mikoz)', 'дерматофития, микоз', 'Infeksiya'),
    ('Onixomikoz', 'онихомикоз', 'Infeksiya'),
    ('Pityriasis versicolor', 'отрубевидный лишай', 'Infeksiya'),
    ('Kandidoz (teri)', 'кандидоз кожи', 'Infeksiya'),
    ('Herpes simplex', 'простой герпес', 'Infeksiya'),
    ('Herpes zoster', 'опоясывающий герпес', 'Infeksiya'),
    ('Molluscum contagiosum', 'контагиозный моллюск', 'Infeksiya'),
    ("Verruca vulgaris (so'gal)", 'бородавка вульгарная', 'Infeksiya'),
    ('Condyloma acuminatum', 'остроконечная кондилома', 'Infeksiya'),
    ('Sifilis (teri)', 'сифилис', 'Infeksiya'),
    ("Qo'tir (scabies)", 'чесотка', 'Infeksiya'),
    ('Demodekoz', 'демодекоз', 'Infeksiya'),
    ('Acne vulgaris', 'акне вульгарные', 'Adneksal'),
    ('Rozatsea', 'розацеа', 'Adneksal'),
    ('Perioral dermatit', 'периоральный дерматит', 'Adneksal'),
    ('Hidradenitis suppurativa', 'гидраденит', 'Adneksal'),
    ('Trixoepitelioma', 'трихоэпителиома', 'Adneksal'),
    ('Pilomatriksoma (Malerb epiteliomasi)', 'пиломатриксома', 'Adneksal'),
    ('Sirinjoma', 'сирингома', 'Adneksal'),
    ('Gidrotsistoma', 'гидроцистома', 'Adneksal'),
    ('Sebatseya giperplaziyasi', 'гиперплазия сальных желёз', 'Adneksal'),
    ('Nevus sebaceus', 'невус сальных желёз', 'Adneksal'),
    ('Sebatseya adenomasi', 'аденома сальных желёз', 'Adneksal'),
    ('Epidermal (epidermoid) kista', 'эпидермальная киста', 'Epidermal'),
    ('Pilar (trixilemmal) kista', 'трихилеммальная киста', 'Epidermal'),
    ('Seboreyali keratoz', 'себорейный кератоз', 'Epidermal'),
    ('Aktinik keratoz', 'актинический кератоз', 'Epidermal'),
    ('Bouen kasalligi (SCC in situ)', 'болезнь Боуэна', 'Epidermal'),
    ('Keratoakantoma', 'кератоакантома', 'Epidermal'),
    ('Yassi hujayrali karsinoma (SCC)', 'плоскоклеточный рак', 'Epidermal'),
    ('Bazal hujayrali karsinoma (BCC)', 'базальноклеточный рак, базалиома', 'Epidermal'),
    ('Teri shoxi (cornu cutaneum)', 'кожный рог', 'Epidermal'),
    ('Yassi epitelial papilloma', 'плоскоклеточная папиллома', 'Epidermal'),
    ('Akrokordon (fibroepitelial polip)', 'акрохордон, мягкая фиброма', 'Epidermal'),
    ('Porokeratoz', 'порокератоз', 'Epidermal'),
    ('Ekstramammar Paget kasalligi', 'экстрамаммарный рак Педжета', 'Epidermal'),
    ('Merkel hujayrali karsinoma', 'карцинома Меркеля', 'Epidermal'),
    ('Chegaraviy (junctional) nevus', 'пограничный невус', 'Melanotsitar'),
    ('Aralash (compound) nevus', 'смешанный невус', 'Melanotsitar'),
    ('Intradermal nevus', 'внутридермальный невус', 'Melanotsitar'),
    ('Displastik nevus', 'диспластический невус', 'Melanotsitar'),
    ('Spitz nevusi', 'невус Шпица', 'Melanotsitar'),
    ('Rid nevusi (pigmentli shpindel)', 'невус Рида', 'Melanotsitar'),
    ("Ko'k nevus", 'голубой невус', 'Melanotsitar'),
    ("Tug'ma melanotsitar nevus", 'врождённый меланоцитарный невус', 'Melanotsitar'),
    ('Lentigo simplex / solaris', 'лентиго', 'Melanotsitar'),
    ('Yuzaki tarqaluvchi melanoma', 'поверхностно распространяющаяся меланома', 'Melanotsitar'),
    ('Tugunli melanoma', 'узловая меланома', 'Melanotsitar'),
    ('Lentigo maligna melanoma', 'лентиго-меланома', 'Melanotsitar'),
    ('Akral lentiginoz melanoma', 'акральная лентигинозная меланома', 'Melanotsitar'),
    ('Melanoma in situ', 'меланома in situ', 'Melanotsitar'),
    ('Dermatofibroma (benign fibroz gistiotsitoma)', 'дерматофиброма', "Yumshoq to'qima"),
    ('Dermatofibrosarkoma protuberans (DFSP)', 'выбухающая дерматофибросаркома', "Yumshoq to'qima"),
    ('Keloid / gipertrofik chandiq', 'келоид, гипертрофический рубец', "Yumshoq to'qima"),
    ('Lipoma', 'липома', "Yumshoq to'qima"),
    ('Neyrofibroma', 'нейрофиброма', "Yumshoq to'qima"),
    ('Shvannoma (neyrilemmoma)', 'шваннома', "Yumshoq to'qima"),
    ('Leyomioma', 'лейомиома', "Yumshoq to'qima"),
    ('Ksantoma / ksantogranuloma', 'ксантома, ксантогранулёма', "Yumshoq to'qima"),
    ('Mikoz fungoides', 'грибовидный микоз', "Yumshoq to'qima"),
    ('Teri B-hujayrali limfomasi', 'В-клеточная лимфома кожи', "Yumshoq to'qima"),
    ('Teri psevdolimfomasi', 'псевдолимфома кожи', "Yumshoq to'qima"),
    ('Mastotsitoz (urticaria pigmentosa)', 'мастоцитоз', "Yumshoq to'qima"),
    ('Morfea (chegaralangan sklerodermiya)', 'морфеа, ограниченная склеродермия', 'Biriktiruvchi'),
    ('Sistem sklerodermiya (teri)', 'системная склеродермия', 'Biriktiruvchi'),
    ('Anetodermiya', 'анетодермия', 'Biriktiruvchi'),
    ('Teri atrofiyasi', 'атрофия кожи', 'Biriktiruvchi'),
    ('Solar elastoz', 'солнечный эластоз', 'Biriktiruvchi'),
    ('Elastosis perforans serpiginosa', 'перфорирующий эластоз', 'Biriktiruvchi'),
    ('Pseudoxanthoma elasticum', 'псевдоксантома эластическая', 'Biriktiruvchi'),
    ('Vitiligo', 'витилиго', 'Pigmentatsiya'),
    ('Melazma', 'мелазма, хлоазма', 'Pigmentatsiya'),
    ('Postinflamator giperpigmentatsiya', 'поствоспалительная гиперпигментация', 'Pigmentatsiya'),
    ("Ochta-dog'li gipomelanoz", 'идиопатический каплевидный гипомеланоз', 'Pigmentatsiya'),
    ('Alopecia areata', 'гнёздная алопеция', 'Pigmentatsiya'),
    ('Androgenetik alopetsiya', 'андрогенетическая алопеция', 'Pigmentatsiya'),
    ('Chandiqli alopetsiya', 'рубцовая алопеция', 'Pigmentatsiya'),
    ('Telogen effluvium', 'телогеновое выпадение волос', 'Pigmentatsiya'),
    ('Amiloidoz (teri)', 'амилоидоз кожи', 'Boshqa'),
    ('Kalsinoz (teri)', 'кальциноз кожи', 'Boshqa'),
    ('Podagra tofusi', 'подагрический тофус', 'Boshqa'),
    ('Mutsinoz', 'муциноз', 'Boshqa'),
    ('Prurigo nodularis', 'узловатая почесуха', 'Boshqa'),
    ('Krapivnitsa (urtikariya)', 'крапивница', 'Boshqa'),
    ('Angioedema', 'отёк Квинке', 'Boshqa'),
    ('Dori toshmasi (dori reaksiyasi)', 'лекарственная сыпь', 'Boshqa'),
    ("Ichki a'zo kasalligida teri o'zgarishi", 'изменения кожи при болезнях внутренних органов', 'Boshqa'),
    ("Chandiq to'qimasi", 'рубцовая ткань', 'Boshqa'),
    ('Normal teri', 'нормальная кожа', 'Boshqa'),
    ("Reaktiv (nospetsifik) yallig'lanish", 'неспецифическое воспаление', 'Boshqa'),
)
